---

language: go

go:
  - 1.x

matrix:
  fast_finish: true

before_install:
  - go get github.com/golang/lint/golint

before_script:
  - golint ./...
  - go vet ./...
  - go test -v -cover ./...

script:
  - go install
  - $GOPATH/bin/tempreader -help

notifications:
  email: false
